server:
  port: 80

eureka:
  client:
    # true 注册自己为服务提供方
    register-with-eureka: false
    # fetch-registry: 集群必须设置为true，才可以配合ribbon使用负载平衡
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #设置与eureka server交互地址

# 设置feign的超时时间；默认等待1s，超时返回错误
ribbon:
  #建立连接所用允许的等待时间
  RealTimeout: 5000
  # 建立连接后读取资源的允许的等待时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以哪个级别监控哪个接口
    com.jw.sc.service.PaymentFeignService: debug