server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #server-addr: 127.0.0.1:1111  #通过nginx注册到nacos上
        #server-addr: 192.168.27.177:1111  #通过nginx注册到nacos上
management:
  endpoints:
    web:
      exposure:
        include: '*'