server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 消费者将要去访问的微服务名称，注册进nacos的服务提供者名称
server-url:
  nacos-user-server: http://nacos-payment-provider