server:
  port: 8001

spring:
  application:
    name: CLOUD-PAYMENT-SERVICE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/myBatis?useSSL=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Pxx1234!
  zipkin:
    base-url: http://localhost:9411 #提交到zipkin网页进行展示
  sleuth:
    sampler:
      probability: 1  #采样率 0-1之间；1表示全部采样


eureka:
  client:
    # true 注册自己为服务提供方
    register-with-eureka: true
    # fetch-registry: 集群必须设置为true，才可以配合ribbon使用负载平衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #设置与eureka server交互地址
  instance:
    # 注册服务后的服务提供主机的名称
    instance-id: payment8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jw.sc.entity