server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  #cloud:
    #alibaba:
      #seata:
        #自定义事务组名称
        #tx-service-group: fsp_tx_default
    nacos:
      discovery:
        #nacos服务中心注册地址
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Pxx1234!
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false

seata:
  enabled: true
  application-id: seata-order-service
  tx-service-group: fsp_tx_default #my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml