
server:
  port: 8801

spring:
  application:
    name: CLOUD-STREAM-PROVIDER
  cloud:
    stream:
      binders:    #绑定rabbitMQ的服务信息
        defaultRabbit:   #用于绑定的名称，用于binding整合
          type: rabbit  #组件类型
          environment:  #rabbitMQ相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        sms1-out-0:
          destination: studyExchange1
        sms2-out-0:
          destination: studyExchange2
    function:
      destination: sms1; sms2

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #设置与eureka server交互地址
  instance:
    leased-renewal-interval-in-seconds: 2 #客户端向服务器发送心跳的时间间隔  默认30s
    leased-expiration-duration-in-seconds: 5  #服务端收到最后一次心跳后等待的时间上限，默认90s；超时将删除服务
    instance-id: send-8801.com    #消息列表显示主机名
    prefer-ip-address: true